### ISSUE TITLE
B2: Certificate verification failed

### ISSUE THREAD

**Issue by LordMike** [wernight/docker-duplicity#3]
I get the below error when trying to backup to B2. Could seem like the container doesn't have an up to date certificates file.
```
Traceback (most recent call last):
  File "/usr/bin/duplicity", line 1537, in <module>
    with_tempdir(main)
  File "/usr/bin/duplicity", line 1531, in with_tempdir
    fn()
  File "/usr/bin/duplicity", line 1369, in main
    action = commandline.ProcessCommandLine(sys.argv[1:])
  File "/usr/lib/python2.7/site-packages/duplicity/commandline.py", line 1117, in ProcessCommandLine
    backup, local_pathname = set_backend(args[0], args[1])
  File "/usr/lib/python2.7/site-packages/duplicity/commandline.py", line 1006, in set_backend
    globals.backend = backend.get_backend(bend)
  File "/usr/lib/python2.7/site-packages/duplicity/backend.py", line 223, in get_backend
    obj = get_backend_object(url_string)
  File "/usr/lib/python2.7/site-packages/duplicity/backend.py", line 209, in get_backend_object
    return factory(pu)
  File "/usr/lib/python2.7/site-packages/duplicity/backends/b2backend.py", line 73, in __init__
    response = urllib2.urlopen(request)
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1241, in https_open
    context=self._context)
  File "/usr/lib/python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)
URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)>
```

**Comment by ghost** [comment]
Could you perhaps give hotio/duplicity a try, it's based on wernight's, but some tweaks and webdav support.
https://github.com/hotio/docker-duplicity/blob/master/Dockerfile

**Comment by wernight** [comment]
I've upgraded to 3.5 but it's hard for me to check as I've no B2. Possibly need to install some python package for TLS. Try and run this in the container before running duplicity in that same container:

    $ apk add --update ca-certificates && update-ca-certificates

**Comment by LordMike** [comment]
I managed to follow @wernight suggestion, and it worked. I ran duplicity first, which failed due to the certificates. Then ran the above command, and re-ran duplicity which proceeded to ask about a Passphrase.

Adding certs to the Dockerfile will probably fix this :).

**Comment by wernight** [comment]
Should be fixed now.
